### PR TITLE
Travis CI: Add Python 3.8

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by etingof** [comment]
Thank you for taking care of 3.8!

I have one question: why did you remove the distro key at places?

**Comment by cclauss** [comment]
__os: linux__ and __dist: xenial__ are the Travis defaults.  Trusty is EoL so I only use it where it is absolutely necessary like for Python 2.6 and 3.3 that Travis does not run on Xenial.

**Comment by etingof** [comment]
Thank you!

**Comment by cclauss** [comment]
Sure.  Did you ever run it on iOS devices?

**Comment by etingof** [comment]
No, I have not tried that.

As for the raw sockets, pysnmp *can* use them for spoofing, but that's just one specific use-case you are unlikely to need.

For crypto, pysnmp relies on pycryptodomex or cryptography. But those are not required unless you want strong crypto support.

**Pull request merged**
