### PR TITLE
[DOC] Fix typo

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by etingof** [comment]
But it is really meant to be `locus`, not `focus`! Where locus is "a particular position or place where something occurs or is situated.".

Does it make sense?

**Comment by johnthagen** [comment]
Ah interesting.  I had never heard that word used that way before, only the mathematical use.  But it looks like that is a valid English definition :)

I would personally suggest re-wording it, but not a big deal either way.

**Comment by etingof** [comment]
They also [use it](https://en.wikipedia.org/wiki/Locus_of_control) in psychology ;)

**Comment by johnthagen** [comment]
Yeah, let's close this. Though a fun discussion about the English language :)

**Pull request closed without merging**
